name: CD

on:
  push:
    branches:
      - 'release/v**'
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release: true
