name: CI

on:
  push:
    branches-ignore:
      - 'release/v**'
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./Dockerfile
      push: false
  standalone-build:
    uses: ./.github/workflows/standalone-build.yml
